export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOAD_MOVIES_REQUEST = 'LOAD_MOVIES_REQUEST';
export const LOAD_MOVIES_SUCCEEDED = 'LOAD_MOVIES_SUCCEEDED';
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED';
